version: '3.1'

services:

  metal-archives-crawler:
    build:
      context: .
    depends_on:
      - mongo
    volumes:
      - .:/app/

  mongo:
    image: mongo
    restart: always
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: {}